name: ${description}
main: plugily.projects.buildbattle.Main
authors: [ PlugilyProjects, Tigerpanzer_02, Tigerpanzer, Plajer, TomTheDeveloper ]
version: ${version}
softdepend: [ Vault, Citizens,  PlaceholderAPI, Parties, Spigot-Party-API-PAF, PartyAndFriends, ViaVersion, ProtocolSupport ]
api-version: 1.13

commands:
  buildbattle:
    description: BuildBattle Commands
    usage: "ยง6Correct usage: /bb [option]"
    aliases: [ bb, buildb ]
  buildbattleadmin:
    description: BuildBattle Admin Commands
    usage: "ยง6Correct usage: /bba [option]"
    aliases: [ bba, buildbadmin ]

permissions:
  buildbattle.admin.*:
    default: op
    children:
      buildbattle.particles: true
      buildbattle.heads: true
      buildbattle.updatenotify: true
      buildbattle.admin: true
      buildbattle.admin.sign.create: true
      buildbattle.admin.sign.break: true
      buildbattle.admin.stopgame: true
      buildbattle.admin.addnpc: true
      buildbattle.admin.addsign: true
      buildbattle.admin.reload: true
      buildbattle.admin.forcestart: true
      buildbattle.admin.forcestart.theme: true
      buildbattle.admin.addplot: true
      buildbattle.admin.removeplot: true
      buildbattle.admin.plotwand: true
      buildbattle.admin.list: true
      buildbattle.admin.delete: true
      buildbattle.admin.create: true
      buildbattle.admin.settheme: true
      buildbattle.admin.supervotes.manage: true
      buildbattle.command.bypass: true