main: pl.plajer.buildbattle3.Main
version: 3.2.3
name: BuildBattle
depend: [WorldEdit]
softdepend: [Vault, PlaceholderAPI, Citizens]
authors: [Plajer, TomTheDeveloper]

commands:
  buildbattle:
    usage: /buildbattle
    description: The main command
    aliases: [buildb, bb]
  buildbattleadmin:
    aliases: [buildba, bba]

permissions:
  buildbattle.admin.*:
    default: op
    children:
      buildbattle.updatenotify: true
      buildbattle.admin: true
      buildbattle.admin.sign.create: true
      buildbattle.admin.sign.break: true
      buildbattle.admin.stopgame: true
      buildbattle.admin.addnpc: true
      buildbattle.admin.addsign: true
      buildbattle.admin.reload: true
      buildbattle.admin.forcestart: true
      buildbattle.admin.addplot: true
      buildbattle.admin.list: true
      buildbattle.admin.delete: true
      buildbattle.admin.create: true
      buildbattle.admin.settheme: true